// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestVoorToets.Data;

#nullable disable

namespace TestVoorToets.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20230404213116_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("TestVoorToets.Data.Models.Author", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Name = "John"
                        },
                        new
                        {
                            Name = "Jane"
                        },
                        new
                        {
                            Name = "Jill"
                        });
                });

            modelBuilder.Entity("TestVoorToets.Data.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorName");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("TestVoorToets.Data.Models.Blog", b =>
                {
                    b.HasOne("TestVoorToets.Data.Models.Author", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TestVoorToets.Data.Models.Author", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
